package com.globalformulae.shiguang.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.globalformulae.shiguang.model.Schedule;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCHEDULE".
*/
public class ScheduleDao extends AbstractDao<Schedule, Long> {

    public static final String TABLENAME = "SCHEDULE";

    /**
     * Properties of entity Schedule.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Description = new Property(2, String.class, "description", false, "DESCRIPTION");
        public final static Property Year = new Property(3, int.class, "year", false, "YEAR");
        public final static Property Month = new Property(4, int.class, "month", false, "MONTH");
        public final static Property Day = new Property(5, int.class, "day", false, "DAY");
        public final static Property Hour = new Property(6, int.class, "hour", false, "HOUR");
        public final static Property Minute = new Property(7, int.class, "minute", false, "MINUTE");
        public final static Property DayOfWeek = new Property(8, int.class, "dayOfWeek", false, "DAY_OF_WEEK");
        public final static Property Status = new Property(9, int.class, "status", false, "STATUS");
        public final static Property Type = new Property(10, boolean.class, "type", false, "TYPE");
    }


    public ScheduleDao(DaoConfig config) {
        super(config);
    }
    
    public ScheduleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCHEDULE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"DESCRIPTION\" TEXT," + // 2: description
                "\"YEAR\" INTEGER NOT NULL ," + // 3: year
                "\"MONTH\" INTEGER NOT NULL ," + // 4: month
                "\"DAY\" INTEGER NOT NULL ," + // 5: day
                "\"HOUR\" INTEGER NOT NULL ," + // 6: hour
                "\"MINUTE\" INTEGER NOT NULL ," + // 7: minute
                "\"DAY_OF_WEEK\" INTEGER NOT NULL ," + // 8: dayOfWeek
                "\"STATUS\" INTEGER NOT NULL ," + // 9: status
                "\"TYPE\" INTEGER NOT NULL );"); // 10: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCHEDULE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Schedule entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(3, description);
        }
        stmt.bindLong(4, entity.getYear());
        stmt.bindLong(5, entity.getMonth());
        stmt.bindLong(6, entity.getDay());
        stmt.bindLong(7, entity.getHour());
        stmt.bindLong(8, entity.getMinute());
        stmt.bindLong(9, entity.getDayOfWeek());
        stmt.bindLong(10, entity.getStatus());
        stmt.bindLong(11, entity.getType() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Schedule entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(3, description);
        }
        stmt.bindLong(4, entity.getYear());
        stmt.bindLong(5, entity.getMonth());
        stmt.bindLong(6, entity.getDay());
        stmt.bindLong(7, entity.getHour());
        stmt.bindLong(8, entity.getMinute());
        stmt.bindLong(9, entity.getDayOfWeek());
        stmt.bindLong(10, entity.getStatus());
        stmt.bindLong(11, entity.getType() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Schedule readEntity(Cursor cursor, int offset) {
        Schedule entity = new Schedule( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // description
            cursor.getInt(offset + 3), // year
            cursor.getInt(offset + 4), // month
            cursor.getInt(offset + 5), // day
            cursor.getInt(offset + 6), // hour
            cursor.getInt(offset + 7), // minute
            cursor.getInt(offset + 8), // dayOfWeek
            cursor.getInt(offset + 9), // status
            cursor.getShort(offset + 10) != 0 // type
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Schedule entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setYear(cursor.getInt(offset + 3));
        entity.setMonth(cursor.getInt(offset + 4));
        entity.setDay(cursor.getInt(offset + 5));
        entity.setHour(cursor.getInt(offset + 6));
        entity.setMinute(cursor.getInt(offset + 7));
        entity.setDayOfWeek(cursor.getInt(offset + 8));
        entity.setStatus(cursor.getInt(offset + 9));
        entity.setType(cursor.getShort(offset + 10) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Schedule entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Schedule entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Schedule entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
